require 'ruby_peter_v/version'
require 'ruby_peter_v/single'
require 'ruby_peter_v/max_with_nil'
require 'ruby_peter_v/set_once'
require 'ruby_peter_v/do_recursively'
require 'ruby_peter_v/define_equality'
